# frozen_string_literal: true

# Magick Configuration
# Generated by: rails generate magick:install
#
# For more configuration options, see:
# https://github.com/andrew-woblavobla/magick

Magick.configure do
  # Configure Redis (optional - gem works without it using memory-only adapter)
  # Uncomment to use Redis:
  # redis url: ENV['REDIS_URL'], namespace: 'magick:features'

  # Configure memory adapter TTL (default: 3600 seconds = 1 hour)
  # memory_ttl 7200 # 2 hours

  # Configure circuit breaker for Redis failures
  # circuit_breaker threshold: 5, timeout: 60

  # Enable async updates for Redis (non-blocking, improves performance)
  # async_updates enabled: true

  # Enable performance metrics tracking
  performance_metrics enabled: true

  # Enable audit logging (every mutation is logged under its real action name)
  audit_log enabled: true

  # Enable versioning (every save creates a version snapshot; allows rollback)
  # max_versions caps the hot window kept in memory/Redis; the ActiveRecord
  # adapter keeps an unlimited archive.
  versioning enabled: true, max_versions: 50

  # Enable deprecation warnings in logs
  warn_on_deprecated enabled: true
end

# Admin UI configuration (optional).
# The Admin UI is CSRF-protected and 404s on unknown feature IDs, BUT
# authentication is opt-in — if you mount the engine without configuring
# `require_role`, the UI will be reachable by anyone who can hit its routes.
# Always wire it to your host app's auth layer. Gating at the router is the
# more robust option, since it covers every route the engine mounts:
#
# # config/routes.rb
# authenticate :admin_user do
#   mount Magick::AdminUI::Engine, at: '/magick'
# end
#
# The built-in hook is the alternative. It gates every Admin UI route, and it
# must be a callable or nil — assigning a bare role name raises
# Magick::ConfigurationError rather than leaving the panel silently open.
#
# Magick::AdminUI.configure do |c|
#   c.require_role = ->(controller) { controller.current_user&.admin? }
#   c.available_roles = %w[admin manager]
#   c.available_tags  = -> { Tag.pluck(:name) }
# end

# Graceful shutdown is handled automatically in Rails via an at_exit hook
# wired by the Railtie. In long-running non-Rails processes (rake tasks,
# CLI tools), call `Magick.shutdown!` explicitly before exit so the
# Redis Pub/Sub subscriber and async metrics thread terminate cleanly.

