# frozen_string_literal: true

# Magick Configuration
# Generated by: rails generate magick:install
#
# For more configuration options, see:
# https://github.com/andrew-woblavobla/magick

Magick.configure do
  # Configure Redis (optional - gem works without it using memory-only adapter)
  # Uncomment to use Redis:
  # redis url: ENV['REDIS_URL'], namespace: 'magick:features'

  # Configure memory adapter TTL (default: 3600 seconds = 1 hour)
  # memory_ttl 7200 # 2 hours

  # Configure circuit breaker for Redis failures
  # circuit_breaker threshold: 5, timeout: 60

  # Enable async updates for Redis (non-blocking, improves performance)
  # async_updates enabled: true

  # Enable performance metrics tracking
  performance_metrics enabled: true

  # Enable audit logging (tracks who changed what, when)
  audit_log enabled: true

  # Enable versioning support (allows rollback)
  versioning enabled: true

  # Enable deprecation warnings in logs
  warn_on_deprecated enabled: true
end
